# Generated by Django 5.2.8 on 2025-11-15 02:18

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_entrada', models.TimeField(default='09:00:00')),
                ('minutos_tolerancia', models.IntegerField(default=15)),
                ('email_gerente', models.EmailField(max_length=254)),
                ('ruta_red_reportes', models.CharField(help_text='Ruta de red para guardar reportes mensuales', max_length=500)),
            ],
            options={
                'verbose_name_plural': 'Configuración del Sistema',
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name_plural': 'Departamentos',
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_empleado', models.CharField(max_length=20, unique=True)),
                ('qr_code', models.ImageField(blank=True, upload_to='qr_codes/')),
                ('qr_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('tiempo_extra_habilitado', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
                ('departamento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='attendance.departamento')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Empleados',
            },
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('hora', models.TimeField(auto_now_add=True)),
                ('tipo_movimiento', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SALIDA_COMIDA', 'Salida a Comida'), ('ENTRADA_COMIDA', 'Entrada de Comida'), ('SALIDA', 'Salida')], max_length=20)),
                ('retardo', models.BooleanField(default=False)),
                ('minutos_retardo', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.empleado')),
            ],
            options={
                'verbose_name_plural': 'Asistencias',
                'ordering': ['-fecha', '-hora'],
            },
        ),
        migrations.CreateModel(
            name='TiempoExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('horas_extra', models.DecimalField(decimal_places=2, max_digits=5)),
                ('descripcion', models.TextField(blank=True)),
                ('aprobado', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.empleado')),
            ],
            options={
                'verbose_name_plural': 'Tiempos Extra',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Visitante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('empresa', models.CharField(blank=True, max_length=200)),
                ('telefono', models.CharField(max_length=20)),
                ('motivo', models.TextField()),
                ('fecha_visita', models.DateField()),
                ('hora_visita', models.TimeField()),
                ('qr_code', models.ImageField(blank=True, upload_to='qr_visitantes/')),
                ('qr_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('confirmado', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('departamento_visita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.departamento')),
            ],
            options={
                'verbose_name_plural': 'Visitantes',
            },
        ),
        migrations.CreateModel(
            name='RegistroVisita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_entrada', models.DateTimeField(auto_now_add=True)),
                ('hora_salida', models.DateTimeField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('visitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.visitante')),
            ],
            options={
                'verbose_name_plural': 'Registros de Visitas',
                'ordering': ['-hora_entrada'],
            },
        ),
    ]
